### ISSUE TITLE
Support wp_viewporter

### ISSUE THREAD

**Issue by dos1** [canonical/mir#2599]
Several clients such as SDL or Waydroid are now using [viewporter](https://wayland.app/protocols/viewporter) protocol in order to crop and/or scale the attached buffer. It's also the recommended way for clients to deal with fractional output scaling.

Mir appears to be missing support for this protocol entirely.

Weston comes with a simple client to verify the implementation: `weston-scaler`.

**Comment by RAOF** [comment]
`wp_viewporter` is a sensible thing to support - a lot of overlay hardware has capabilities that map very directly onto the interface exposed by `wp_viewporter`, so this provides optimisation opportunities that would otherwise not be available.

That you can use it to kinda implement fractional scaling is somewhat of a side effect; ideally fractional scaling would be negotiated directly, with the compositor's explicit participation, rather than worked around with a protocol that can be made to sorta get the right effect.

**Comment by JamiKettunen** [comment]
Mir v2.11's missing `wp_viewporter` support is now visible on https://wayland.app/protocols/viewporter#compositor-support, when support is added (and new version tagged) https://github.com/vially/wayland-explorer should get a follow-up PR by running [`wlprobe`](https://github.com/PolyMeilex/wlprobe) against `mir_demo_server` and replacing the existing `src/data/compositors/mir.json` ^^

**Comment by AlanGriffiths** [comment]
Closed by #3445
