### ISSUE TITLE
Alt+Tab restores minimized windows, even if they don't end up focused

### ISSUE THREAD

**Issue by Saviq** [canonical/mir#3323]
Steps:
- have at least three non-obscuring windows open
- minimize one of them
- cycle through Alt+Tab to reach the other un-minimized window

Expected:
- the minimized window remains minimized

Current:
- the minimized window is restored

Also: should minimized windows be moved to the bottom of the stack? That would certainly alleviate this issue.

**Comment by mattkae** [comment]
We could move them to the bottom of the stack I suppose, but I don't think that fully solves the problem. The problem is that you that the user has no indication that minimized windows are alt-tabbable (e.g. in gnome-shell they show the window in the preview even though it's minimized).

Perhaps we just don't allow minimized apps to be alt-tabbable until we can use some other indication?

**Comment by Saviq** [comment]
Well, yeah, _while_ Alt+Tabbing, we'd have to restore them, but they should go back to minimized unless you actually choose the un-minimized one.

Yeah it's all wonky without a proper visual switcher, but maybe we can do something better.

**Comment by Saviq** [comment]
To rephrase: the only _lasting_ effect of a Alt+Tab/` "session" should be the raising/focusing of the window that was in front when Alt is released.

It may well be we have to refactor it altogether to e.g. copy the stack and manipulate that rather than the original, right until the end.
