### ISSUE TITLE
Screenshots no longer respect output scale

### ISSUE THREAD

**Issue by RAOF** [canonical/mir#3461]
When screenshotting with grim to see if I could reproduce #3431 to see if I could *test* #3456, I instead discovered that
* I could indeed screenshot on my AMD/NVIDIA system, but
* Those screenshots only took up 1/4 of the captured output (presumably the screenshot buffer's size-in-pixels is based on the scaled size, and the screenshot didn't take that into account)

![For example](https://github.com/canonical/mir/assets/804339/96c1da10-9dea-474d-9ec3-b7be75be58cc)

(If you have a look there there's a perfectly normal screenshot in the bottom quarter, and three fully-transparent rectangles around it.)

**Comment by mattkae** [comment]
Same thing on the X11 platform FYI, so it isn't hardware related

**Comment by mattkae** [comment]
Oof, this was trickier than I thought to track down. Here's what's happening:

- In `wl_screencopy_v1.h`, we define a struct called `FrameParams` which holds the output area and the buffer size. Both of these values are currently set to the _scaled size_
- The output space area size _should be_ the scaled size because this is the viewport
- The buffer size however should be the _unscaled size_ because this is the size of the buffer that we want to fill (which should be the entire output contents)

**Comment by mattkae** [comment]
But also: area screenshots should also define their area in screen coordinates
