### ISSUE TITLE
We don't handle brightness controls

### ISSUE THREAD

**Issue by AlanGriffiths** [canonical/mir#3654]
Press the brightness controls when running a Mir based compositor (e.g. Miriway)

**Expect:** brightness changes
**Actual:** brightness unchanged

----

A workaround is to switch to VT1 and adjust the brightness on the greeter the switch back

**Comment by RAOF** [comment]
I'm not *sure* this is something that Mir should deal with, rather than a session component; as long as something can notice the key events, just poking the relevant files in `/sys/` is all that's necessary. (I don't believe that any of the other compositors handle brightness setting, other than forwarding the relevant events)

**Comment by AlanGriffiths** [comment]
Yeah, maybe this should be on Miriway _et alia_
