### ISSUE TITLE
Numlock LED does not change

### ISSUE THREAD

**Issue by sdvallejo** [canonical/mir#620]
I’m creating an electron kiosk app following this tutorial: https://tutorials.ubuntu.com/tutorial/electron-kiosk. 1

All works great, but I’m having a problem with the lock of the numeric pad. By default the numeric pad is disabled but I need to change this. Is there any way to change the default status?

If I press the num lock key, the numeric keyboard enables, but the LED not change. So is difficult for the user to know if it is enabled or not.

**Comment by AlanGriffiths** [comment]
We should be updating state via libinput

**Comment by RAOF** [comment]
This should not be very difficult; I'll take a look.

**Comment by AlanGriffiths** [comment]
> This should not be very difficult; I'll take a look.

@RAOF any news? :wink:

**Comment by RAOF** [comment]
Ok.

So, what needs to happen here is:
* The `Input` platform abstraction needs to grow a "set LEDs" interface; the libinput platform will call [`libinput_device_led_update`](https://wayland.freedesktop.org/libinput/doc/latest/api/group__device.html#gafdb3ddfb91e6bd38b6356a5bb51547ad) to implement this.
* When changing keymap, we need to pull out the the LED index with [`xkb_keymap_led_get_index`](https://xkbcommon.org/doc/current/group__components.html#gae7f970e4ba807657c3cc214fc13c998d)
* When updating XKB modifier state, we need to check what LEDs are active with [`xkb_state_led_index_is_active`](https://xkbcommon.org/doc/current/group__state.html#gaa5a02e6f26ccd29b95e32d6fcb8f8149)
* We then need to call the "set LEDs" interface on the appropriate input devices (which, *I think*, is all of them, because we don't have per-device XKB state?)
